/** Map Yahoo / dashboard country names to ISO 3166-1 alpha-2 for flagcdn.com */
const MAP = {
  "United States": "us",
  "USA": "us",
  US: "us",
  India: "in",
  "United Kingdom": "gb",
  UK: "gb",
  Germany: "de",
  Japan: "jp",
  China: "cn",
  Canada: "ca",
  Australia: "au",
  France: "fr",
  "South Korea": "kr",
  Korea: "kr",
  Switzerland: "ch",
  Netherlands: "nl",
  Sweden: "se",
  Italy: "it",
  Spain: "es",
  Brazil: "br",
  Mexico: "mx",
  Singapore: "sg",
  "Hong Kong": "hk",
  Taiwan: "tw",
  Ireland: "ie",
  Belgium: "be",
  Norway: "no",
  Finland: "fi",
  Denmark: "dk",
  Austria: "at",
  Israel: "il",
  "United Arab Emirates": "ae",
  "Saudi Arabia": "sa",
  Russia: "ru",
  Poland: "pl",
  Indonesia: "id",
  Thailand: "th",
  Malaysia: "my",
  Philippines: "ph",
  Vietnam: "vn",
  "New Zealand": "nz",
  "South Africa": "za",
  Turkey: "tr",
  Argentina: "ar",
  Chile: "cl",
  Colombia: "co",
  Peru: "pe",
  Portugal: "pt",
  Greece: "gr",
  Czechia: "cz",
  "Czech Republic": "cz",
  Hungary: "hu",
  Romania: "ro",
  Egypt: "eg",
  Nigeria: "ng",
  Pakistan: "pk",
  Bangladesh: "bd",
};

export function countryToIso2(country) {
  if (!country || typeof country !== "string") return null;
  const k = country.trim();
  return MAP[k] || null;
}
